### ISSUE TITLE
如何提交预测结果呢？

### ISSUE THREAD

**Issue by WrRan** [gitdevqiang/Covid-19-Sentiment-Analysis#1]
@gitdevqiang 您好，请问该数据集的验证集及测试集的预测结果要在哪个地方进行提交呢？是否有实时的排名网站？

**Comment by gitdevqiang** [comment]
Hi WrRan, Please go to Kaggle competition website: https://www.kaggle.com/c/sentiment-analysis-of-covid-19-related-tweets/overview

**Comment by WrRan** [comment]
Thanks!
